version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:prod
    networks:
      - app-net

  postgres:
    image: postgres:alpine
    restart: always
    shm_size: 128mb
    container_name: postgres 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge